
export default function Head() {
  return (
    <>
        <title>IMDb-Code</title>
        <meta content="width=device-width, initial-scale-1" name="viewport"/>
        <meta  name="description" content="Generated by Ramiro App"/>
        <link rel="icon" href="/favicon.ico" />
    </>
  )
}
